### ISSUE TITLE
problematic ValueError: syntax error in JSON

### ISSUE THREAD

**Issue by adi160885** [tomellericcardo/EVIL-ESP#6]
I use uPyCraft but there is this error, please help, thanks in advance
exec(open('./main.py').read(),globals())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 118, in <module>
  File "<string>", line 16, in __init__
  File "<string>", line 24, in load_config
ValueError: syntax error in JSON

**Comment by adi160885** [comment]
can be used
